##############################################################################
#
# method_figures.R
#
# Thao P. Le, Thomas K. Waring, Chris M. Baker
#
# 2023
# 
# Using the "recommended_samples.csv" file generated by generate_df.R,
# we can output figures in the methods section of the paper 
# 
##############################################################################
library(tidyverse)
library(tidyr)
source("core_functions.R")

data_name <- 'outputs/recommended_samples.csv'
DF <- tryCatch(read.csv(data_name), error = function(e){
  stop("Didn't find past values.")
})


##############################################################################
# This code plots Figure...
##############################################################################


plot_name <- 'outputs/recommended_samples_plot_N'

prior_N = 10000
prior_y_list <- seq(1,20,1)

plot_data <- DF %>% filter((T1_level_percent==95) & (prior_samples==prior_N) &(past_leakage  %in% prior_y_list))
plot_data$T2_percent <- sapply(plot_data$T2_percent, function(x){paste0(x,"%")})


ggplot(data =plot_data, mapping = aes(x=past_leakage, y=optimal_samples,group=T2_percent,)) + geom_line(aes(colour=T2_percent)) +
  labs(x='Past leakage',y='Minimum recommended next sample size',color=expression('T'["risk"]))  +
  theme(legend.position = c(0.2, 0.75))
ggsave(paste0(plot_name, prior_N, '.png'), width = 4, height =6)


##############################################################################
# Other figure....
##############################################################################

min_samples = DF %>% filter(T1_level_percent == 94)
colnames(min_samples)[which(names(min_samples)=="optimal_samples")] = "min_samples"
min_samples$T1_level_percent <- NULL
min_samples$T1_percent <- NULL

mid_samples = DF %>% filter(T1_level_percent == 95)
colnames(mid_samples)[which(names(mid_samples)=="optimal_samples")] = "mid_samples"
mid_samples$T1_level_percent <- NULL
mid_samples$T1_percent <- NULL

max_samples = DF %>% filter(T1_level_percent == 96)
colnames(max_samples)[which(names(max_samples)=="optimal_samples")] = "max_samples"
max_samples$T1_level_percent <- NULL
max_samples$T1_percent <- NULL

plot_data = merge(min_samples,mid_samples,by=c("prior_samples","past_leakage","T2_percent"))
plot_data = merge(plot_data,max_samples,by=c("prior_samples","past_leakage","T2_percent"))

plot_name <- 'outputs/optimal_samples_plot_N'

plot_data <- data.frame(lapply(plot_data, function(x) as.numeric(as.character(x))))
plot_data <- plot_data %>% filter(past_leakage <= floor(0.002 * prior_samples))
colnames(plot_data)[3] <- "T_risk_percent"

colnames(plot_data)[3] <- "T_risk"


prior_N <- 10000

prior_y_list <- seq(1,20,1)

data_N = plot_data %>% filter((prior_samples == prior_N) &(past_leakage  %in% prior_y_list))
data_N$T_risk <- sapply(data_N$T_risk, function(x){paste0(x,"%")})

ggplot(data = data_N, mapping = aes(x=past_leakage,group=T_risk)) +
  geom_ribbon(aes(ymin=min_samples,ymax=max_samples,fill=T_risk),alpha=0.4) +
  geom_line(aes(y=mid_samples,color=T_risk)) +
  labs(x='Past leakage',y='Minimum recommended next sample size') + theme(legend.position = "none")
ggsave(paste0(plot_name, prior_N, '_ranges2.png'), width = 4, height = 6)





